import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#ffffff',
        width: '100%',
        paddingTop: 72,
    },
    title: {
        fontSize: 20,
        fontWeight: '500',
        marginBottom: 16,
        color: '#333',
        maxWidth: '90%',
        alignSelf: 'center',
    },
    subtitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#000000',
        marginTop: 52,
        textAlign: 'center',
        width: '80%',
        alignSelf: 'center',
        maxWidth: '90%',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 28,
        borderColor: '#e3e3e3',
        borderWidth: 1,
        padding: 8,
        marginTop: 16,
        width: '90%',
        minHeight: 40,
        alignSelf: 'center',
        maxWidth: '100%',
    },
    iconPlaceholder: {
        width: 24,
        height: 24,
        borderRadius: 12,
        marginRight: 8,
        maxWidth: 24,
        maxHeight: 24,
    },
    searchText: {
        color: '#000',
        fontSize: 14,
        flexShrink: 1,
    },
    buttonPlaceholder: {
        width: '90%',
        minHeight: 90,
        borderRadius: 14,
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: 30,
        elevation: 2,
        maxWidth: '100%',
    },
    buttonText: {
        fontSize: 16,
        color: '#000000',
        fontWeight: '600',
        alignSelf: 'flex-start',
        marginLeft: 20,
        maxWidth: '90%',
    },
    buttonTextSecondary: {
        fontSize: 16,
        color: '#f5f5f5',
        fontWeight: '600',
        alignSelf: 'flex-start',
        marginLeft: 20,
        maxWidth: '90%',
    },
});