import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#ffffff',
        width: '100%',
        paddingTop: 72,
    },
    title: {
        fontSize: 20,
        fontWeight: '500',
        color: '#000000',
        marginTop: 52,
        textAlign: 'center',
        width: '80%',
        alignSelf: 'center',
        maxWidth: '90%',
    },
    rowButtons: {
        width: '100%',
        alignItems: 'center',
        marginTop: 26,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
    },
    buttonPlaceholder: {
        backgroundColor: '#619B8A',
        borderRadius: 20,
        paddingVertical: 5,
        paddingHorizontal: 15,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        minHeight: 44,
        minWidth: 100,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
    },
    buttonTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        textAlign: 'center',
    },
    buttonSubtitle: {
        color: 'white',
        fontSize: 14,
        textAlign: 'center',
    },
    dropdownButton: {
        borderWidth: 2,
        borderColor: '#619B8A',
        borderRadius: 20,
        paddingVertical: 5,
        paddingHorizontal: 15,
        justifyContent: 'center',
        minHeight: 44,
        minWidth: 100,
        alignItems: 'center',
        backgroundColor: '#fff',
        marginHorizontal: 8,
    },
    dropdownContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 10,
    },
    dropdownText: {
        fontSize: 16,
        marginRight: 8,
        color: '#000',
    },
    dropdownIcon: {
        width: 12,
        height: 12,
        resizeMode: 'contain',
    },
    picker: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: '#619B8A',
        opacity: 0,
        width: '100%',
        height: '100%',
    },
});