import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#eee',
        width: '100%',
        paddingTop: 80,
    },
    navbar: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        backgroundColor: '#FCCA46',
        paddingVertical: 24,
        paddingHorizontal: 16,
        alignItems: 'flex-start',
        flexDirection: 'row',
        zIndex: 10,
    },
    title: {
        fontSize: 16,
        marginTop: 18,
        fontWeight: '500',
        color: '#000000',
    },
    iconPlaceholder: {
        width: 24,
        marginTop: 18,
        height: 24,
        borderRadius: 12,
        marginRight: 16,
        maxWidth: 24,
        maxHeight: 24,
    },
    assuntos: {
        fontSize: 18,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 16,
        color: '#333',
        maxWidth: '90%',
        alignSelf: 'center',
    },
    balaoContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    balaoInner: {
        position: 'relative',
        width: 280,
        height: 180,
        alignItems: 'center',
    },
    balaoImg: {
        marginTop: 50,
        width: 280,
        height: 100,
        position: 'absolute',
        top: 0,
        left: 100,
        zIndex: 1,
    },
    balaoText: {
        position: 'absolute',
        marginTop: 50,
        marginLeft: 150,
        top: 24,
        left: 20,
        width: 140,
        color: '#333',
        fontSize: 15,
        fontWeight: 'bold',
        transform: [{ rotate: '4.91deg' }],
        textAlign: 'center',
        zIndex: 2,
    },
    raposaImg: {
        width: 340,
        height: 200,
        position: 'absolute',
        top: 140,
        left: -20,
        zIndex: 0,
    },
    assuntosContainer: {
        alignItems: 'center',
        marginTop: 170,
    },
    assuntosBox: {
        width: '90%',
        alignItems: 'flex-start',
        borderRadius: 14,
        borderColor: '#FCCA46',
        borderWidth: 2,
        padding: 16,
        backgroundColor: '#eee',
    },
    assuntoText: {
        marginVertical: 8,
        fontSize: 14,
        color: '#222',
    },
    assuntoBold: {
        fontWeight: 500,
    },
    assuntoParenteses: {
        color: '#B5B5B5',
    },
});